apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-serviceaccount
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-rolebinding
subjects:
- kind: ServiceAccount
  name: fluentd-serviceaccount
roleRef:
  kind: ClusterRole
  name: fluentd-reader
  apiGroup: rbac.authorization.k8s.io
